### PR TITLE
add gnome-platform snap support

### PR DESCRIPTION
**Pull request by diddledan**
this PR adds support for a smaller distribution by leaning upon the gnome-3-24 snap. Also allows for ubuntu default themes to work as they're included in the platform snap.

### CODE REVIEW

**Comment by popey** [comment]
I built and installed this in cleanbuild on my laptop, then ran corebird. I haven't yet installed gnome-platform snap, but tried building just the corebird snap alone. When I run it, I get this. Am I doing something wrong?

```
alan@hal:~$ corebird 
cat: /home/alan/snap/corebird/x1/openh264/version: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  505k  100  505k    0     0   994k      0 --:--:-- --:--:-- --:--:--  994k
/snap/corebird/x1/bin/desktop-launch: line 136: 20589 Bad system call         bunzip2 $H264DIR/libopenh264.so.bz2
No schema files found: doing nothing.
/snap/corebird/x1/bin/desktop-launch: line 375: /snap/corebird/x1/usr/bin/corebird: No such file or directory
```

**Comment by diddledan** [comment]
hmm, that doesn't look right. first I thought I removed the cat of "version" in favour of a more consistent-with-desktop-helpers method of recognising updates. Second, the Schema files not being found is really wrong. The schema files are compiled by the desktop-launch script. And no usr/bin/corebird?! How badly have I messed up, I wonder. Let me pull the PR into a separate dir and investigate.

**Comment by diddledan** [comment]
Was your source tree modified before you pulled the PR? Can you try pulling the PR to a fresh clone? I just built from a clean git clone of this repo (not my own repo) and checked out the PR followed by a cleanbuild. That new clean build does not exhibit the behaviour you describe.

**Comment by diddledan** [comment]
Can you try again, I've refactored considerably to remove the dependency on the jhbuild plugin. This version compiles to about 35MB on my system.

**Comment by diddledan** [comment]
closing this in favour of pr #2

**Pull request closed without merging**
